name: Test

on:
    push:
      branches:
      - action_test

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install qemu-user-static
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
