name: Test

on:
    push:
      branches:
      - action_test

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg BASEIMAGE=${BASEIMAGE} \
            --push \
            -t ${IMAGE}:${VERSION} \
            -t ${IMAGE}:latest \
            .
