name: publish to dockerhub

on:
    push:
      branches:
      - master

jobs:
  build:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: set up buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build (and publish) main image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg BASEIMAGE=alpine:3.12 \
            --push \
            -t fopina/openvpn:2.4.9.1 \
            -t fopina/openvpn:latest \
            .
      
      - name: build (and publish) qrcode helper
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg BASEIMAGE=fopina/openvpn:2.4.9.1 \
            --push \
            -f Dockerfile.helper \
            -t fopina/openvpn:helper-2.4.9.1 \
            -t fopina/openvpn:helper \
            .
